name: aoc
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  args: ^2.4.2
  characters: ^1.3.0
  collection: ^1.18.0
  quiver: ^3.2.1
  tuple: ^2.0.2

dev_dependencies:
  fd_lints: ^2.2.0
